'use client';

import React, { useState, useEffect, useRef, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { useAuth, useUser, SignInButton } from '@clerk/nextjs';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {
    PenTool, ArrowLeft, CheckCircle2, FileText, Gavel,
    AlertTriangle, Mail, FileSignature, ChevronDown, Download,
    Sparkles, Loader2, RotateCcw, Copy, Check
} from 'lucide-react';

// ─── Constants ──────────────────────────────────────────────────────────────

const DRAFT_TYPES = [
    { id: 'complaint', label: 'Complaint', icon: AlertTriangle, color: 'bg-rose-50 border-rose-200 text-rose-600', activeColor: 'bg-rose-500', desc: 'File a formal complaint to authorities' },
    { id: 'legal_notice', label: 'Legal Notice', icon: Gavel, color: 'bg-indigo-50 border-indigo-200 text-indigo-600', activeColor: 'bg-indigo-500', desc: 'Send a legal notice to a party' },
    { id: 'appeal', label: 'Appeal Letter', icon: Mail, color: 'bg-amber-50 border-amber-200 text-amber-600', activeColor: 'bg-amber-500', desc: 'Appeal a decision or order' },
    { id: 'affidavit', label: 'Affidavit', icon: FileSignature, color: 'bg-emerald-50 border-emerald-200 text-emerald-600', activeColor: 'bg-emerald-500', desc: 'Sworn written statement of facts' },
    { id: 'rti', label: 'RTI Application', icon: FileText, color: 'bg-blue-50 border-blue-200 text-blue-600', activeColor: 'bg-blue-500', desc: 'Right to Information request' },
    { id: 'general', label: 'General Draft', icon: PenTool, color: 'bg-slate-50 border-slate-200 text-slate-600', activeColor: 'bg-slate-500', desc: 'General purpose document' },
];

const API_BASE = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:8000';

// ─── PDF Export using pdf-lib ────────────────────────────────────────────────

async function exportToPDF(content: string, title: string) {
    const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');

    const pdfDoc = await PDFDocument.create();
    const timesRoman = await pdfDoc.embedFont(StandardFonts.TimesRoman);
    const timesBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);

    const margin = 60;
    const pageWidth = 595;  // A4 width in pts
    const pageHeight = 842; // A4 height in pts
    const textWidth = pageWidth - margin * 2;
    const lineHeight = 16;
    const fontSize = 11;
    const titleFontSize = 16;

    // Strip markdown to plain text
    const plainText = content
        .replace(/#{1,6}\s+/g, '')
        .replace(/\*\*([^*]+)\*\*/g, '$1')
        .replace(/\*([^*]+)\*/g, '$1')
        .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1')
        .replace(/^[-*]\s+/gm, '• ')
        .replace(/`([^`]+)`/g, '$1');

    const lines = plainText.split('\n');
    const wrapped: string[] = [];
    for (const line of lines) {
        if (line.trim() === '') { wrapped.push(''); continue; }
        let remaining = line;
        while (remaining.length > 0) {
            let chunkEnd = remaining.length;
            while (timesRoman.widthOfTextAtSize(remaining.slice(0, chunkEnd), fontSize) > textWidth && chunkEnd > 1) chunkEnd--;
            wrapped.push(remaining.slice(0, chunkEnd));
            remaining = remaining.slice(chunkEnd);
        }
    }

    let page = pdfDoc.addPage([pageWidth, pageHeight]);
    let y = pageHeight - margin;

    // Title
    const titleLines = title.split('\n');
    for (const tl of titleLines) {
        page.drawText(tl, { x: margin, y, font: timesBold, size: titleFontSize, color: rgb(0.16, 0.42, 0.94) });
        y -= titleFontSize + 6;
    }
    y -= 8;
    page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 1, color: rgb(0.8, 0.8, 0.8) });
    y -= 16;

    for (const line of wrapped) {
        if (y < margin + lineHeight) {
            page = pdfDoc.addPage([pageWidth, pageHeight]);
            y = pageHeight - margin;
        }
        if (line.trim()) page.drawText(line, { x: margin, y, font: timesRoman, size: fontSize, color: rgb(0.1, 0.1, 0.1) });
        y -= lineHeight;
    }

    // Footer
    const pages = pdfDoc.getPages();
    pages.forEach((p, i) => {
        p.drawText(`Generated by CivicPulse AI  |  Page ${i + 1} of ${pages.length}`, {
            x: margin, y: 30, font: timesRoman, size: 8, color: rgb(0.6, 0.6, 0.6),
        });
    });

    const pdfBytes = await pdfDoc.save();
    const blob = new Blob([pdfBytes], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_')}_CivicPulse.pdf`;
    a.click();
    URL.revokeObjectURL(url);
}

// ─── Main Component ──────────────────────────────────────────────────────────

function DraftCreationPageInner() {
    const searchParams = useSearchParams();
    const router = useRouter();
    const { getToken, isSignedIn, isLoaded } = useAuth();
    const { user } = useUser();

    const topicFromURL = searchParams.get('topic') || '';
    const sourceFromURL = searchParams.get('source') || 'direct'; // 'chat' | 'live' | 'direct'

    const [step, setStep] = useState<'confirm' | 'form' | 'generating' | 'done'>(
        topicFromURL ? 'confirm' : 'form'
    );
    const [topic, setTopic] = useState(topicFromURL);
    const [draftType, setDraftType] = useState<string>('complaint');
    const [additionalContext, setAdditionalContext] = useState('');
    const [generatedContent, setGeneratedContent] = useState('');
    const [streamingContent, setStreamingContent] = useState('');
    const [copied, setCopied] = useState(false);
    const [isExportingPDF, setIsExportingPDF] = useState(false);
    const scrollRef = useRef<HTMLDivElement>(null);

    // Infer draft type from topic URL
    useEffect(() => {
        if (!topicFromURL) return;
        const t = topicFromURL.toLowerCase();
        if (t.includes('complaint')) setDraftType('complaint');
        else if (t.includes('notice')) setDraftType('legal_notice');
        else if (t.includes('appeal')) setDraftType('appeal');
        else if (t.includes('affidavit')) setDraftType('affidavit');
        else if (t.includes('rti')) setDraftType('rti');
    }, [topicFromURL]);

    // Autoscroll during streaming
    useEffect(() => {
        if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }, [streamingContent]);

    const handleGenerate = async () => {
        if (!topic.trim()) return;
        setStep('generating');
        setStreamingContent('');
        setGeneratedContent('');

        const selectedType = DRAFT_TYPES.find(t => t.id === draftType);
        const prompt = `You are CivicPulse, an expert Indian legal document drafter. Generate a complete, professional ${selectedType?.label || 'legal document'} based on the following:\n\nTopic / Situation: ${topic}\n\nAdditional Details: ${additionalContext || 'None provided'}\n\nInstructions:\n- Format the document professionally.\n- Include all standard sections for a ${selectedType?.label}.\n- Use formal legal language appropriate for Indian courts or authorities.\n- Add placeholder text like [YOUR NAME], [DATE], [ADDRESS] where required.\n- Structure with clear headings and numbered points.\n\nGenerate the full document now:`;

        try {
            const token = isSignedIn ? await getToken() : null;

            const headers: Record<string, string> = { 'Content-Type': 'application/json' };
            if (token) headers['Authorization'] = `Bearer ${token}`;

            const response = await fetch(`${API_BASE}/api/chat/stream`, {
                method: 'POST',
                headers,
                body: JSON.stringify({
                    session_id: `draft_${Date.now()}`,
                    message: prompt,
                    language: 'en',
                }),
            });

            if (!response.ok || !response.body) throw new Error('Generation failed');

            const reader = response.body.getReader();
            const decoder = new TextDecoder();
            let full = '';

            while (true) {
                const { done, value } = await reader.read();
                if (done) break;

                const chunk = decoder.decode(value, { stream: true });
                for (const line of chunk.split('\n')) {
                    if (line.startsWith('data: ')) {
                        try {
                            const data = JSON.parse(line.slice(6));
                            if (data.done) break;
                            if (data.content) {
                                full += data.content;
                                setStreamingContent(full);
                            }
                        } catch { }
                    }
                }
            }

            setGeneratedContent(full);
            setStep('done');
        } catch (err) {
            console.error('Draft generation error:', err);
            setGeneratedContent('An error occurred while generating the draft. Please try again.');
            setStep('done');
        }
    };

    const handleCopy = async () => {
        await navigator.clipboard.writeText(generatedContent);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleExportPDF = async () => {
        setIsExportingPDF(true);
        try {
            const typeLabel = DRAFT_TYPES.find(t => t.id === draftType)?.label || 'Draft';
            await exportToPDF(generatedContent, `${typeLabel} — ${topic.slice(0, 60)}`);
        } finally {
            setIsExportingPDF(false);
        }
    };

    // ─── Not Loaded ────────────────────────────────────────────────────────
    if (!isLoaded) {
        return (
            <div className="min-h-screen flex items-center justify-center" style={{ background: 'linear-gradient(135deg, #F8FBFF 0%, #E6F2FF 100%)' }}>
                <div className="w-10 h-10 border-4 border-[#2A6CF0] border-t-transparent rounded-full animate-spin" />
            </div>
        );
    }

    // ─── Layout Shell ──────────────────────────────────────────────────────
    return (
        <div className="min-h-screen" style={{ background: 'linear-gradient(135deg, #F8FBFF 0%, #E6F2FF 100%)' }}>
            {/* Top Bar */}
            <div className="sticky top-0 z-30 backdrop-blur-md bg-white/80 border-b border-slate-100 px-4 py-3 flex items-center gap-3">
                <button
                    onClick={() => router.back()}
                    className="p-2 rounded-xl text-slate-500 hover:text-[#2A6CF0] hover:bg-indigo-50 transition-all"
                >
                    <ArrowLeft className="w-5 h-5" />
                </button>
                <div className="flex items-center gap-2.5">
                    <div className="w-8 h-8 bg-gradient-to-br from-[#2A6CF0] to-[#4CB782] rounded-xl flex items-center justify-center shadow-sm">
                        <PenTool className="w-4 h-4 text-white" />
                    </div>
                    <div>
                        <h1 className="text-sm font-bold text-slate-900 leading-none">Draft Creator</h1>
                        <p className="text-[10px] text-slate-400 mt-0.5">AI-powered legal documents</p>
                    </div>
                </div>
                <div className="ml-auto flex items-center gap-2 text-xs text-slate-400 font-medium">
                    <span className={`w-1.5 h-1.5 rounded-full ${step === 'done' ? 'bg-emerald-400' : step === 'generating' ? 'bg-amber-400 animate-pulse' : 'bg-[#2A6CF0]'}`} />
                    {step === 'confirm' ? 'Review Context' : step === 'form' ? 'Configure' : step === 'generating' ? 'Generating…' : 'Done'}
                </div>
            </div>

            <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">

                {/* ─── STEP 1: CONFIRM (triggered from Chat/Live) ─── */}
                {step === 'confirm' && (
                    <div className="bg-white rounded-3xl shadow-[0_4px_24px_rgba(42,108,240,0.08)] border border-white overflow-hidden">
                        <div className="p-6 border-b border-slate-50 bg-gradient-to-r from-indigo-50/60 to-blue-50/40">
                            <div className="flex items-start gap-3">
                                <div className="w-10 h-10 bg-indigo-100 rounded-2xl flex items-center justify-center shrink-0">
                                    <Sparkles className="w-5 h-5 text-indigo-600" />
                                </div>
                                <div>
                                    <p className="text-xs font-bold text-indigo-500 uppercase tracking-wider mb-1">
                                        Detected from {sourceFromURL === 'live' ? 'Live Mode' : 'Chat'}
                                    </p>
                                    <h2 className="text-lg font-bold text-slate-900">We understood your request</h2>
                                    <p className="text-sm text-slate-500 mt-1">Review and confirm the details before generating</p>
                                </div>
                            </div>
                        </div>

                        <div className="p-6 space-y-5">
                            <div>
                                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Your Request</label>
                                <div className="mt-2 p-4 bg-slate-50 rounded-2xl border border-slate-100">
                                    <p className="text-slate-800 text-sm leading-relaxed">"{topic}"</p>
                                </div>
                                <button
                                    onClick={() => setStep('form')}
                                    className="mt-2 text-xs text-[#2A6CF0] hover:underline font-medium"
                                >
                                    Edit this →
                                </button>
                            </div>

                            <div>
                                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Document Type</label>
                                <div className="mt-2 grid grid-cols-2 sm:grid-cols-3 gap-2">
                                    {DRAFT_TYPES.map(type => {
                                        const Icon = type.icon;
                                        const isSelected = draftType === type.id;
                                        return (
                                            <button
                                                key={type.id}
                                                onClick={() => setDraftType(type.id)}
                                                className={`p-3 rounded-2xl border-2 text-left transition-all flex items-start gap-2.5 ${isSelected ? 'border-[#2A6CF0] bg-indigo-50' : 'border-slate-100 bg-white hover:border-slate-200'}`}
                                            >
                                                <Icon className={`w-4 h-4 mt-0.5 shrink-0 ${isSelected ? 'text-[#2A6CF0]' : 'text-slate-400'}`} />
                                                <div>
                                                    <p className={`text-xs font-bold ${isSelected ? 'text-[#2A6CF0]' : 'text-slate-700'}`}>{type.label}</p>
                                                    <p className="text-[10px] text-slate-400 leading-tight mt-0.5">{type.desc}</p>
                                                </div>
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            <div>
                                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Additional Details <span className="normal-case text-slate-400 font-normal">(optional)</span></label>
                                <textarea
                                    value={additionalContext}
                                    onChange={e => setAdditionalContext(e.target.value)}
                                    rows={3}
                                    placeholder="Parties involved, dates, specific clauses, desired outcome…"
                                    className="mt-2 w-full px-4 py-3 rounded-2xl border border-slate-200 text-sm text-slate-800 placeholder-slate-300 focus:outline-none focus:border-[#2A6CF0] focus:ring-2 focus:ring-[#2A6CF0]/10 resize-none transition-all"
                                />
                            </div>

                            <button
                                onClick={handleGenerate}
                                className="w-full flex items-center justify-center gap-2.5 py-4 bg-gradient-to-r from-[#2A6CF0] to-[#4A8CF8] text-white font-bold text-base rounded-2xl shadow-[0_4px_14px_rgba(42,108,240,0.35)] hover:shadow-[0_6px_20px_rgba(42,108,240,0.45)] hover:scale-[1.01] transition-all"
                            >
                                <CheckCircle2 className="w-5 h-5" />
                                Confirm & Generate Draft
                            </button>
                        </div>
                    </div>
                )}

                {/* ─── STEP 2: FORM (direct /draftcreation visit) ─── */}
                {step === 'form' && (
                    <div className="space-y-5">
                        <div className="text-center pb-2">
                            <div className="w-14 h-14 bg-gradient-to-br from-[#2A6CF0] to-[#4CB782] rounded-3xl flex items-center justify-center mx-auto mb-4 shadow-[0_4px_14px_rgba(42,108,240,0.3)]">
                                <PenTool className="w-7 h-7 text-white" />
                            </div>
                            <h2 className="text-2xl font-extrabold text-slate-900 tracking-tight">Create a Legal Draft</h2>
                            <p className="text-slate-500 text-sm mt-2">AI-generated documents for complaints, legal notices, and more</p>
                        </div>

                        <div className="bg-white rounded-3xl shadow-[0_4px_24px_rgba(42,108,240,0.08)] border border-white p-6 space-y-5">
                            <div>
                                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">What do you need to draft?</label>
                                <textarea
                                    value={topic}
                                    onChange={e => setTopic(e.target.value)}
                                    rows={4}
                                    placeholder="E.g., I need to file a complaint about my landlord not returning my security deposit of ₹50,000 after 3 months…"
                                    className="mt-2 w-full px-4 py-3 rounded-2xl border border-slate-200 text-sm text-slate-800 placeholder-slate-300 focus:outline-none focus:border-[#2A6CF0] focus:ring-2 focus:ring-[#2A6CF0]/10 resize-none transition-all"
                                />
                            </div>

                            <div>
                                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Document Type</label>
                                <div className="mt-2 grid grid-cols-2 sm:grid-cols-3 gap-2">
                                    {DRAFT_TYPES.map(type => {
                                        const Icon = type.icon;
                                        const isSelected = draftType === type.id;
                                        return (
                                            <button
                                                key={type.id}
                                                onClick={() => setDraftType(type.id)}
                                                className={`p-3 rounded-2xl border-2 text-left transition-all flex items-start gap-2.5 ${isSelected ? 'border-[#2A6CF0] bg-indigo-50' : 'border-slate-100 bg-white hover:border-slate-200'}`}
                                            >
                                                <Icon className={`w-4 h-4 mt-0.5 shrink-0 ${isSelected ? 'text-[#2A6CF0]' : 'text-slate-400'}`} />
                                                <div>
                                                    <p className={`text-xs font-bold ${isSelected ? 'text-[#2A6CF0]' : 'text-slate-700'}`}>{type.label}</p>
                                                    <p className="text-[10px] text-slate-400 leading-tight mt-0.5">{type.desc}</p>
                                                </div>
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            <div>
                                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Additional Details <span className="normal-case text-slate-400 font-normal">(optional)</span></label>
                                <textarea
                                    value={additionalContext}
                                    onChange={e => setAdditionalContext(e.target.value)}
                                    rows={3}
                                    placeholder="Parties involved, specific dates, clauses, desired outcome…"
                                    className="mt-2 w-full px-4 py-3 rounded-2xl border border-slate-200 text-sm text-slate-800 placeholder-slate-300 focus:outline-none focus:border-[#2A6CF0] focus:ring-2 focus:ring-[#2A6CF0]/10 resize-none transition-all"
                                />
                            </div>

                            <button
                                onClick={handleGenerate}
                                disabled={!topic.trim()}
                                className="w-full flex items-center justify-center gap-2.5 py-4 bg-gradient-to-r from-[#2A6CF0] to-[#4A8CF8] text-white font-bold text-base rounded-2xl shadow-[0_4px_14px_rgba(42,108,240,0.35)] hover:shadow-[0_6px_20px_rgba(42,108,240,0.45)] hover:scale-[1.01] transition-all disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:scale-100"
                            >
                                <Sparkles className="w-5 h-5" />
                                Generate Draft
                            </button>
                        </div>

                        <p className="text-center text-[11px] text-slate-400">
                            CivicPulse is an AI assistant, not a lawyer. Always consult a qualified advocate for legal matters.
                        </p>
                    </div>
                )}

                {/* ─── STEP 3: GENERATING ─── */}
                {step === 'generating' && (
                    <div className="bg-white rounded-3xl shadow-[0_4px_24px_rgba(42,108,240,0.08)] border border-white overflow-hidden">
                        <div className="p-5 border-b border-slate-50 flex items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="w-8 h-8 bg-indigo-100 rounded-xl flex items-center justify-center">
                                    <Loader2 className="w-4 h-4 text-indigo-600 animate-spin" />
                                </div>
                                <div>
                                    <p className="text-sm font-bold text-slate-900">Generating your draft…</p>
                                    <p className="text-xs text-slate-400">{DRAFT_TYPES.find(t => t.id === draftType)?.label} · AI writing</p>
                                </div>
                            </div>
                            <div className="flex gap-1">
                                {[0, 0.15, 0.3].map((d, i) => (
                                    <div key={i} className="w-2 h-2 bg-[#2A6CF0]/40 rounded-full animate-bounce" style={{ animationDelay: `${d}s` }} />
                                ))}
                            </div>
                        </div>

                        <div ref={scrollRef} className="p-6 max-h-[60vh] overflow-y-auto overscroll-contain">
                            <div className="prose prose-slate prose-sm max-w-none">
                                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                    {streamingContent || 'Generating…'}
                                </ReactMarkdown>
                            </div>
                        </div>
                    </div>
                )}

                {/* ─── STEP 4: DONE ─── */}
                {step === 'done' && (
                    <div className="space-y-4">
                        {/* Header banner */}
                        <div className="bg-gradient-to-r from-emerald-50 to-teal-50 border border-emerald-100 rounded-3xl p-5 flex items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 bg-emerald-100 rounded-2xl flex items-center justify-center">
                                    <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                                </div>
                                <div>
                                    <p className="font-bold text-emerald-800 text-sm">Draft Generated Successfully</p>
                                    <p className="text-xs text-emerald-600">{DRAFT_TYPES.find(t => t.id === draftType)?.label} · {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
                                </div>
                            </div>
                            <div className="flex gap-2">
                                <button onClick={handleCopy} className="flex items-center gap-1.5 px-3 py-2 bg-white border border-emerald-200 text-emerald-700 text-xs font-bold rounded-xl hover:bg-emerald-50 transition-all">
                                    {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                                    {copied ? 'Copied!' : 'Copy'}
                                </button>
                                <button
                                    onClick={handleExportPDF}
                                    disabled={isExportingPDF}
                                    className="flex items-center gap-1.5 px-3 py-2 bg-[#2A6CF0] text-white text-xs font-bold rounded-xl hover:bg-[#2259D6] transition-all disabled:opacity-70 shadow-[0_2px_8px_rgba(42,108,240,0.3)]"
                                >
                                    {isExportingPDF ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
                                    {isExportingPDF ? 'Exporting…' : 'Save PDF'}
                                </button>
                            </div>
                        </div>

                        {/* Document viewer */}
                        <div className="bg-white rounded-3xl shadow-[0_4px_24px_rgba(42,108,240,0.08)] border border-white overflow-hidden">
                            <div className="px-6 py-4 border-b border-slate-50 flex items-center justify-between">
                                <div className="flex items-center gap-2">
                                    <FileText className="w-4 h-4 text-slate-400" />
                                    <span className="text-sm font-bold text-slate-700">Document Preview</span>
                                </div>
                                <button
                                    onClick={() => { setStep('form'); setGeneratedContent(''); setStreamingContent(''); }}
                                    className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-[#2A6CF0] font-medium transition-colors"
                                >
                                    <RotateCcw className="w-3.5 h-3.5" />
                                    Start Over
                                </button>
                            </div>

                            <div className="p-6 max-h-[65vh] overflow-y-auto overscroll-contain">
                                <div className="prose prose-slate prose-sm max-w-none">
                                    <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                        {generatedContent}
                                    </ReactMarkdown>
                                </div>
                            </div>
                        </div>

                        <p className="text-center text-[11px] text-slate-400">
                            Review this document carefully. CivicPulse is an AI. Always verify with a qualified advocate before submitting.
                        </p>
                    </div>
                )}
            </div>
        </div>
    );
}

export default function DraftCreationPage() {
    return (
        <Suspense fallback={
            <div className="min-h-screen flex items-center justify-center" style={{ background: 'linear-gradient(135deg, #F8FBFF 0%, #E6F2FF 100%)' }}>
                <div className="w-10 h-10 border-4 border-[#2A6CF0] border-t-transparent rounded-full animate-spin" />
            </div>
        }>
            <DraftCreationPageInner />
        </Suspense>
    );
}
